project:
  type: website
  output-dir: docs

website:
  title: "Hanna Velicer's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Resume.qmd
      - Projects.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

