---
title: "Resume"
---

## **Education**

------------------------------------------------------------------------

**Colorado State University** - Fort Collins, CO - Expected Graduation: May 2026

-   Bachelor of Science in Ecosystem Science and Sustainability					         

-   Minor in Zoology			         

-   Honors Program

-   Dean’s List; Warner College of Natural Resources

**Shawnee Mission South High School** - Overland Park, KS - May 2022

-   Summa Cum Laude, 4.72 GPA

-   Kansas ACT and State Scholar

\

## **Work History**

------------------------------------------------------------------------

**Rehabilitation Intern** - San Juan Island, Washington - June-August 2024

Internship with Wolf Hollow Wildlife Rehabilitation Center

-   Conducted daily diet preparations and enclosure cleanings for harbor seals, raptors, songbirds, and small mammals

-   Assisted staff with medicine administration and acquired syringe and tube feeding skills

-   Responded to calls from the public and facilitated the process of capture and delivery to the center

\

**Seasonal Natural Resource Technician** - Edgerton, KS - May-August 2023

Internship with Johnson County Parks and Recreation District

-   Removed and controlled invasive plant species throughout Big Bull Creek Park

-   Created habitat for native quail population

-   Daily data input into ArcGIS about the location of invasive plant species in the park and past controlled burns

\

## **Additional Experience**

------------------------------------------------------------------------

**Behavior and Biology of African Mammals** - Kenya, Africa - May 2024

-   Faculty-led study abroad program focusing on observation and data collection on animal behavior methods

-   Acquired and developed practical field skills including behavioral observation and camera trapping

\

**Volunteer** - Rescued Friends Animal Sanctuary, Fort Collins, CO - January-May 2024

Nonprofit organization housing and caring for abused and neglected farm animals

-   Managed everyday food preparation and pen cleanliness for goats, chickens, pigs, cows, and donkeys

-   Worked alongside head caretaker to monitor daily health for 150+ animals

\

**Animal Specialist In Training** - Rolla, MO - 2019-2021

Exclusive leadership position awarded by director invitation at Cub Creek Science and Animal Camp

-   Received extensive training to work independently with and care for 300+ exotic and domestic animal species

-   Conducted daily husbandry tasks including food preparation and cleaning enclosures

-   Lead weekly educational talks for campers on animal habitat and care

\

**Animal Camp Jamaica** - July 2021

-   Marine biology summer program focusing on ocean habitats, coral reef science, and preservation

-   Participated in community service with local marine conservation programs

-   Acquired comprehensive knowledge of marine life and study the natural habitats
